# data: data$V1, data$V2, data$V3...
# V1 is factorial, V2 is numerical, V3 is outcome

# show different groups in V1
levels(data$V1)
# count $V1 in different groups
table(data$V1)


# main effect plot
library(gplots)
plotmeans(V3 ~ V1, data = data,
xlab = "  ", ylab = "  ", main="Main effect of treatment")

# Box plot
boxplot(len ~ supp * dose, data=dat, frame = FALSE, col = c("#00AFBB", "#E7B800"), ylab="Tooth Length")

# ggplot Visulization
library(ggplot2)
ggplot(Machines, aes(x = Machine, y = score, group = Worker, col = Worker)) +
geom_point() + stat_summary(fun = mean, geom = "line") + theme_bw()

# ggplot color and shape
ggplot(mpg, aes(x = displ, y = hwy, color = drv, shape = drv, linetype = drv)) +
    geom_smooth(se = F, method = 'loess') + 
    geom_point() + 
    scale_linetype_manual(values = c('twodash', 'longdash', 'dashed')) + 
    theme_bw() + 
    scale_color_manual(values = c("#0073C2FF", "#EFC000FF", "#868686FF"))
    
# interaction plot
interaction.plot(x.factor = Wage$occupation, #x-axis variable
                 trace.factor = Wage$ethnicity, #variable for lines
                 response = Wage$wage, #y-axis variable
                 ylab = "Wage",
                 xlab = "occupation",
                 col = c("pink", "blue","yellow"),
                 lty = 1, #line type
                 lwd = 2, #line width
                 trace.label = "ethnicity")
